name: BlockRacing
version: '2.0'
main: fun.oyama.blockracing.Main
api-version: 1.20
authors: [ LQ_Snow ]
#depend: [TitleManager]
description: The first team to collect the required blocks wins
commands:
  tp:
    usage: "/tp <Teammate>"
    description: "TP to teammate."
  locate:
    usage: "/locate <Structure | Biome>"
    description: "Locate structure or biome."
  brdebug:
    description: "brdebug."